require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - lib/jwt-aws-kms.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - '*.gemspec'